[build]
  command = "gatsby build"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="YOUR FLOTIQ API KEY"
  SNIPCART_API_KEY="YOUR SNIPCART API KEY"
  GA_TRACKING_ID="YOUR GA TRACKING ID"
